services:
  ragflow-cpu:
    environment:
      DEEPDOC_LARGE_PAGE_MAX_ZOOMIN: "6"
      OCR_DET_LIMIT_SIDE_LEN: "1280"
      OCR_DET_LIMIT_TYPE: "max"
      TABLE_AUTO_ROTATE: "true"

  ragflow-gpu:
    environment:
      DEEPDOC_LARGE_PAGE_MAX_ZOOMIN: "6"
      OCR_DET_LIMIT_SIDE_LEN: "1280"
      OCR_DET_LIMIT_TYPE: "max"
      TABLE_AUTO_ROTATE: "true"
